### ISSUE TITLE
Fetch Latest Jnanam dBase for V1

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#107]
We need to be able to download the current version of the Jnanam dbase. Either we do this on each new release of an upgrade or we have some kind or runtime frame work.

**Comment by soapdog** [comment]
Working on it... it is a bit tricky. I am going to ship a stack that downloads a new database and overwrites the current one. We should use that before issueing an update to the app.

**Comment by soapdog** [comment]
Working on it... it is a bit tricky. I am going to ship a stack that downloads a new database and overwrites the current one. We should use that before issueing an update to the app.

Just created a script that is inside ```/andre``` on devhap called ```dump_jnanam.sh```, the idea is to run this on a cronjob. This script created a new ```jnanam.sqlite.gz``` on the same folder. It currently goes from a 190mb+ MySQL dump file to a 6.2mb compressed SQLite database. Not bad...

**Comment by soapdog** [comment]
The uncompressed file is about 25mb, which I believe is ok.

**Comment by Brahmanathaswami** [comment]
@soapdog 

I'll use this task moving forward: OK we have several issues

- I discovered, e.g. numerous records with 'Available"  in the title. Also lyrics do not expose "not approved for public" so if a lyrics record is deprecated. it may still appear in the app which fetches all the metadata for a song. 
 - I can go on line and scrub the dbase of all these records and repackage. But only new users will get it. 
 - Similarly, we have volunteers working continuously on categorizing quotes and Video and other media. The categories table (and all related ones, the category_tree, category_item, category_quotes"  have been updated.
- So in our updates we may revise code to reflect changes in the database. 
- users with preinstalled dbase where items are local will never get changes, because our scripts look at the local item and categories tables(s)
 - we either need to create some kind of client side request for updates of the already installed dbase  OR we need to 
 - *always* replace Jnanam on every updated. Now that it is down <7MB it seems the latter is the simplest option.   above you say "ship a stack that downloads a new database and overwrites the current one" OK ... I think you mean "for development" but we need that in the app itself. And some way to trigger this on update to a new version. Probably we can just store the build number in the local documents user settings file?

**Comment by Brahmanathaswami** [comment]
OK the chron is working, the gzip daily is working. I fetched a new copy.. our new code is working... it replaced the old dBase in my Docs folder on start up... I'm marking this issue closed... even though it will still be a task in every version upgrade...
