### ISSUE TITLE
Manage Data Interface

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#144]
- pull nightly.. note the last commit which has an update to the loading routine for Jnanam, which check to see if the mDigest or checksum changed and replaces the old one.. has not been tested yet.
- create new branch "manage data"
- go to /modules/settings/settings.livecode
- create a new card (2) - name the card "Manage Data" (if you can think of a better term let me know... but these seems to make sense, at least on iOS, where "Cellular Data" is the common label.
- UX: Present user with different folders based on media types
- Show total of everything in given media type
- if user taps on one media type: opens to screen with all files
- for books, in fact for all media types these will be subfolders... but the users should not know that.  i.e. we don't allow them to go deeper; there is no point... 
- user sees the files/folders with total data
- on the right is the option to delete.
Don't worry too much about making the UI "pretty" for now... I will get Korana to design something nice after you code it... I want you to finish the screens first *before* she does the design, because in this case, design should follow function and not the other way around... 
- NOTE: we have a new generic "backscript" "lib_Sivasiva" where we are setting up handlers that are more straight forward and "deprecating" David's handlers. So please check there for anything you might use and not his older libraries. If you have a just few commands or functions that make sense to be used globally, rather than create yet another behavior, you may consider using this library for those... I want to try to not create more and more independent behaviors/libs unless the use case really calls for them.

**Comment by soapdog** [comment]
understood. working on it

**Comment by soapdog** [comment]
Implementing a **Media Manager Library** in file ```lib_MediaManager.livecodescript```. This library has no UI, it just provides the features needed to build the module.

**Comment by soapdog** [comment]
New library placed on ```feature-media-management``` branch. 

The function to find out the sizes occupied by the subfolders of a given folder is working. With this function we can easily find how much _audio, books, art_ or other folders occupy on disk. By passing a folder such as _books_ to the same function, we find out how much each book occupy. Very flexible.

Will proceed to create the routines to remove items and then the stack to show an interface for these features.

**Comment by Brahmanathaswami** [comment]
Excellent: HQ says they should have the patch for Android done by Dec 15... I hope to have this data manager interface ready, because Android users are telling me they need it...

**Comment by Brahmanathaswami** [comment]
I think we should try using a simple scrolling field to list media items and their sizes 

Title or file is. [tab] 2.5MB

We don’t need fancy icons or sub group rows like we use on the journal... this is just a utility UI

**Comment by Brahmanathaswami** [comment]
File_id. Not “file is”

**Comment by Brahmanathaswami** [comment]
complete for now
