### ISSUE TITLE
Double Click Bug When Go Back to Portal Stack

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#145]
Click on  "Monastery Websites" the new architecture is: this just goes to another card in the portal stack and the portal is prebuilt…

but if you click on, for example, "Monthly Newsletters" it will launch the view_SivaSivaBrowser stack, and load a URL in the browser widget…

so far, so good

But now click the back arrow at the bottom of the left of the app icon bottom tool bar… go back to the portalStack with to go to a different web site… double click very quickly on any of the links like "Meet the Monks"

On android the app will crash immediately.

but try this on either iOS or Android

double click quick on the back arrow in the app icons on the bottom left…

the app will crash everytime.

Also if we go out to another stack like "Gems" and click twice on the back arrow it will crash the app. If I do this on the desktop it breaks on the Go_PortalLink line with an execution error.

**Comment by jacquegay** [comment]
I accidentally saved some stacks in my own branch that I want to discard. What's the git command to ignore my changes and checkout nightly?

**Comment by Brahmanathaswami** [comment]
If you are in nightly now?  you can always do

git stash

and it will take you back to the state of the branch as it was before your changes, then you can pull.

yes, you should pull nightly, then do 

git checkout -b double-click-back-fix

and work in a separate branch for this... since you may be touching some of the core libs (which is OK) we want your branch to be separate for now.

**Comment by jacquegay** [comment]
got it, thanks

**Comment by jacquegay** [comment]
I think I've isolated the problem but am not familiar enough with the library structure to know where to put a fix. There are a couple of ways to deal with it too, so we should probaly brainstorm because the change will ripple out everywhere and something else could break.

**Comment by Brahmanathaswami** [comment]
Aum

Good

retreat days here… I will be back on duty on Sunday… but you may be off, so I let's connect Monday evening your time on this, OK? Or anytime that works for you….


Svasti Astu, Be Well
Brahmanathaswami
www.himalayanacademy.com<http://www.himalayanacademy.com> Get the SivaSiva App today (for iPhone and iPad)
https://itunes.apple.com/us/app/sivasiva/id1271260502?mt=8

**Comment by jacquegay** [comment]
How's 9:30 my time tonight? I think that's 5:30 PM your time, is that too late for your schedule? We're off daylight savings time which is why there's only 4 hours difference now. I could do a half hour earlier if that's better.

**Comment by Brahmanathaswami** [comment]
perfect.

ping me on Slack first…


Svasti Astu, Be Well
Brahmanathaswami
www.himalayanacademy.com<http://www.himalayanacademy.com> Get the SivaSiva App today (for iPhone and iPad)
https://itunes.apple.com/us/app/sivasiva/id1271260502?mt=8

**Comment by Brahmanathaswami** [comment]
fixed although buttons a very unreponsive in Android.
