### ISSUE TITLE
Calendar Module

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#146]
- [x] City picker to pull calendar .ics from minimela.com
- [x] save to user documents folder
- [ ] parse to create array
- [x] show 90 days in scrolling field
- [x] top of card show month range with forward and back 1 month at a time (but showing 90 days each time you move forward 1 month)
- [x] tap on a day to see all the info for the day... top of "all data" includes summary and julian date
- [ ] Add user Reminder icon top right open input option for user to add their own "event"
    - data items: event "title-summary" (constrain lenght) | Date |Begin time | end time | note/descdription field
    - event title- date and begin and end time shows in calendar section  for that day
   - tap on something to see the whole reminder entry plus Note... with options to
      - delete | forward to a new date | change times | email to a friend
- [x] date picker to jump forward in time (perhaps regular calendar widget pop up?  there are lots of those around... or some other easy method to jump to future week
- [ ] link to simple glossary of terms
-[ ] link to the full text of the Hindu Calendar book (its small..I think we can just store the html on disk.
- [ ] We will need to add the hook to the journal entry as well as the tracker (I can do that later)

**BR assignments:**
- [ ] create small glossary
- [ ] turn Panchangam book into clean html

**Comment by Brahmanathaswami** [comment]
@jacquegay OK I think that's all I can think of right off the bat...

**Comment by Brahmanathaswami** [comment]
@ jacque... BCalendars available here....

If you want me to get that list, I can....

https://www.minimela.com/dev/index.php?main_page=page&id=16

is the page with the list of cities

**Comment by jacquegay** [comment]
Got it and wrote the URL translator handler before dinner. :) Thanks, I should have just gone to that web page before asking you.

**Comment by jacquegay** [comment]
@Brahmanathaswami , you wanted the asterisks removed from the descriptions, right?

**Comment by Brahmanathaswami** [comment]
yes...

**Comment by Brahmanathaswami** [comment]
@jacquegay pull first...4

0) merge Nightly

1) the Choose Your City, pullup, Release city, and submit button all black. You need set the forecolor and background. otherwise all black on iOS  ...  I did it...otherwise could not what was going on iOS. save that and rebuild again iOS

2) the top of the screen still show not showing all the elements. It not obeying fullScreenMode. The calendar shows but the icon showing the country pick is off screen. (i think the elements who show at bottom. Set a 50 "toolbar" above that current navigation, put the icon done that, we were some other things later. (like it lexicon)

3) The mobile scroller for month view and the day  view  - neither work.

4) I think the city field show be hidden until one chosen.  Otherwise the user thinks they have do something their.

**Comment by Brahmanathaswami** [comment]
forward future development to next version

**Comment by Brahmanathaswami** [comment]
close because this is badly word, Not action items. general "TO DO" lst
