### ISSUE TITLE
Lexicon Bug in iOS -- Urgent

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#175]
You need to pull Nightly. to make sure you are could up.

These lexicon was failing  both in iOS and Android. It determined that you debug code was interfering. I had leave the debug JS handler in the browser body, but in the card Script is comment is out and out few of the other "put" statements. And now it works on Andriod, but for some reason/webkit Safari will not response have you dismiss they key board. It you type "aah" and click "Done" on the key board, the app locks up! 

An android there is no "Done" button... you have to click a few letters and click off the keyboard, this getTheDefinition works as expected, not on iOS.

Consider this urgent!

**Comment by soapdog** [comment]
@Brahmanathaswami I will get to this once I am in London.

**Comment by soapdog** [comment]
@Brahmanathaswami working on it now.

In the future, when doing bug reports, we need to be more direct and specific about what is failing and how to reproduce. You're mention the bug is with keyboard, but it is where? In search? It is also specially good if the bug report has a screenshots.

**Comment by Brahmanathaswami** [comment]
on iOS

* you click inside field to enter a few characters
* Keyboard pop ups
* enter a few characters
* click on "Done"

The keyboard remains on screen and you are stuck there.

on Android

* you click inside field to enter a few characters
* Keyboard pop ups
* enter a few characters
* There is no "done" button, 
* but you click on the app (not the keyboard) and the keyboard goes away

**Comment by soapdog** [comment]
@Brahmanathaswami working on it now.

Thanks for the detailed recipe. It is late here, I've built most of the code but haven't tried it on a phone yet. I will test it on a real device tomorrow and finish fixing this.

**Comment by soapdog** [comment]
@Brahmanathaswami I've fixed the web app to handle _Enter_ key which is what mobile keyboards send when you press _done_ or _go_. On both Android and iOS there is always a button near the lower right corner to send _Enter_. I am trapping that event and unfocusing the _search box_ which causes the keyboard to close.

**Comment by soapdog** [comment]
The following work was done to solve this issue:

* ✔️ upgraded from Elm 0.18 to Elm 0.19 (huge space saving, the new lexicon bundle.js is half the size of previous one.)
* ✔️ added new `onEnter` event to the _search box_, now pressing the mobile keyboard _done_ or _go_ key will cause the keyboard to disappear.
* ✔️ reverted bad changes in the lexicon stack that were breaking the app. 
* ✔️ switched from remote copies of Noto Font and Font Awesome to local ones.

_PS: I tested this fix on Android and it works._

**Comment by Brahmanathaswami** [comment]
it is working in 9.0.2.rc1
