### ISSUE TITLE
Footer is not place on the bottom and Android

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#177]
NOTE: 
 - I was placing the footer based Ralph Library to set the card rect. But we now know that the screen rect is not reported on Android
 - I then hide the Home  button
 - and then manually did the geometry to get the remaining three buttons on the right place. Partly an experiment so I learn manage postioning 

CHANGES: (Sept 23)
 - I included the new    mobileSetFullScreenRectForOrientations, "0,0,414,736"  for FSM 
 - Instead of use Ralph Library,I used the 'the rect of this card'  in my layout handler, and hopefully that works

@soapdog please download the new branch "fixAndroid-sep23" 
  - The only thing I pushed were the changes to portal stack footer. Please test, just for that, see if I fixed it. (has nothing to with LC.... I coded the geometry! just learning how)  look at behavior to the card on home screen at tell how it looks now.  It should work across all the cards,

(this whole index/portal navigation is deprecated, It was done by one here who has no sense of UI/UX and have to use it, but now  I have approval from a new plan for the whole navigation in Siva Siva app. We can talk about the one day after you find a place for your cats :-0)

**Comment by soapdog** [comment]
Swami,

The fix didn't work. Also that rect you're setting by hand will not work for my phone, it has a different resolution than that. Below are some shots from the fix, they look exact the same as before:

![photo_2018-09-24_13-04-22](https://user-images.githubusercontent.com/23247/45951174-67dbfe00-bffa-11e8-8a60-acba1f683790.jpg)

![photo_2018-09-24_13-04-14](https://user-images.githubusercontent.com/23247/45951175-67dbfe00-bffa-11e8-97dd-d786a41d837a.jpg)

**Comment by bwmilby** [comment]
May want to test the version in branch `bwm-responsive-1`.  On  iPhone X and Pixel the navigation does move to the bottom on the cards of the portal stack.  For Surprise, you need to touch the back (<) button to get to the page that has been adjusted so far.  See issue #231 for some screenshots.
