### ISSUE TITLE
Journal: Bug on Android

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#184]
- [ ]    all the web entries show wrong title.
- [ ]    The web entries which were videos from youtube have duplicated empty entries (See shot)
- [x]     Filter by activity broken (see shot)
- [x]     Filter by favorites is broken and doesn't filter at all.
- [x]     Any action on the journal takes multiple seconds to load.

We might consider redoing the journal differently...

**Comment by Brahmanathaswami** [comment]
I would like to try datagrid eventually. It really cool.  current doesn't scroll well but they have to fix it

**Comment by soapdog** [comment]
I've been working on a complete new journal stack. It is already working a lot better! It is still a work in progress but it renders fast and it renders correctly regardless of the screen rect.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23247/46422350-11726c00-c72c-11e8-88c3-807e28549395.gif)

Be aware that the conversion of a video to GIF, which is what I used to make the animation above reduces the frame rate, it is much better in the real stack.

Testing the new stack is a bit tricky at the moment because I had to patch the `Siva-Siva-App.json` and the navigation button that leads to the Journal. This will not be needed for the final version, it is because I want to have both Journals available here so that I can compare stuff before replacing one with the other.

Also **it is important to notice that the new journal stack is a binary stack** with its source in it, I will only move to a behavior script once it is fully working. So please, don't edit it because I will not be able to merge it back.

**Comment by soapdog** [comment]
The black bar in the animation above is because the android recorder doesn't capture its own android navigation bar. Notice how the journal layouts correctly while the portal uses letterboxes

**Comment by soapdog** [comment]
Filtering and setting favorites works:

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/23247/46473579-8ef3b600-c7d8-11e8-97bf-d39c33c23374.gif)

Preparing for replacing one journal with the other.

**Comment by soapdog** [comment]
Tested the new nightly on Android. There are some instabilities but it is already working better than the new Journal.

**Comment by Brahmanathaswami** [comment]
Closed for now

**Comment by Brahmanathaswami** [comment]
ln gem if had set the journal entry to the database, in the json tDataA, the path of the image and the quote numbers. These are saved, but click in the journal is not resuming to the same quote.

 dispatch "journalresume" to stack tEntryA["module"] with tDataA, tEntryAgit 

I have uploaded a version that works see branch "small-1-2-3-fixes" and compare to "nightly"
![2018-10-07_08-42-49](https://user-images.githubusercontent.com/3675722/46585791-1a578c00-ca11-11e8-830d-a46b49ad8686.png)

**Comment by Brahmanathaswami** [comment]
@soapdog this is for you

**Comment by soapdog** [comment]
begun merging branch `small-1-2-3-fixes` into `nightly`.

**Comment by soapdog** [comment]
merged.

**Comment by soapdog** [comment]
the code merged doesn't work as expected. The bugs are in `gems` and `listen`, they are not handling the `journalresume` handler correctly.

**Comment by Brahmanathaswami** [comment]
The Quote is saved now with the url to the picture.

one  problem in it quote have unicode diacritical marks:

"The pujārī performs strict ablutions..." etc

comes in
![2018-10-12_09-43-22](https://user-images.githubusercontent.com/3675722/46890679-4739e380-ce03-11e8-82b4-43c2f9f31ed3.png)
 the journal as raw text. 

The pujƒÅrƒ´ performs strict ablution...
you will need use 

textEncode(stringToEncode, encoding)

and 

textDecode(binaryData, encoding)

or something else to maintain the unicode the pDataA [json string}

**Comment by Brahmanathaswami** [comment]
1. Go to PathToSiva on desktop
2. go to lesson one
3. Click back to the Portals
4. click on the journal 
--Results: take you back to the lesson.

try this same thing an Android
1. Go to PathToSiva on desktop
2. go to lesson one
3. Click back to the Portals
4. click on the journal 
It goes cover card  and stops there. The app hungs

this code is reacting different on Andriod (I have yet to test on iOS)

`
on journalResume pData,pEntryA -- sent from journal stack
   close stack "journal"
   put pData["card"] into tCd
   goCd tCd
   if tCd begins with "lesson" then
      put pData["lessonNum"] into tNum
      send "loadLesson tNum" to this cd
   end if
end journalResume

command goCd pCdName,pEffect -- optional effect param
  if the short name of this cd = pCdName then exit goCd
  if pEffect = "" then put "plain" into pEffect
  put (pCdName begins with "lesson") into tIslesson
  lock screen for visual effect
  if there is a cd pCdName then
    go cd pCdName
  else if tIslesson then
    go cd "lessonView"
    send "loadLesson (word 2 of pCdName)" to this cd
  else if pCdName = "home" then -- return to project
    put "push right" into pEffect
    send "portal_Link read" to me in 0
    exit goCd
  end if
  toggleHeader not tIslesson and (the number of cd pCdName > 2)
  unlock screen with visual effect pEffect fast
end goCd
`

**Comment by Brahmanathaswami** [comment]
On iOS we see is happening with Path to Siva.
1. we launch activity
2. it to stack, opening cd 1 very quickly; but into message queue we how have a pending
   send "gotoPathIndex" to me in 4  second (issue on card 1)
3. next it got right away to the card we want..
4. but, after 4 second passes, it goes to the index card. 

in iOS it doesn't have

on Android, 
1 ) opens that stack to the cover card
2) 'hangs" on something.

**Comment by Brahmanathaswami** [comment]
You need to set the orientation of journal go portrait 

1) go to LOOK
2) hit the History movie
3) then click the journal
4) The journal tries to render in landscape orientation.

**Comment by Brahmanathaswami** [comment]
I solved the issue of going back to same quote, it does not "hang" but keep going to the same quote and picture everytime because sJournalData has data in it!   after your render card, set it to empty, and every works. You have to do this order, so all instances of calling a quote should be

fetchQuote
fetchImage
/ you do the other way, you won't same image. you get the quote,  but next image will be random because sJournalData in empty.

`  [snip} set the filename of img "gems-image" to sivasiva_AssetFolder() & tNextImagePath   
   setLastImagePath tNextImagePath  
   show image "gems-Image" 
   
   put empty into sJournalData
   /  other wise you get the same quote over and over again!`

**Comment by Brahmanathaswami** [comment]
``

**Comment by Brahmanathaswami** [comment]
Is this function being used? If not, can I delete it? it confusing

Line 254 of 
model_SivaSivaJournal'

`on journalresume pDataA, pEntryA
   put "Error: no one could handle journalresume, going for the default behavior"
   --put "Launching" && pEntryA["module"]
   portal_GoStack pEntryA["module"]
end journalresume`

**Comment by soapdog** [comment]
@Brahmanathaswami if you delete this function the whole app will break. This function is there so that it traps the `journalresume` message in case it is not handled by other modules. Basically, if you try to resume something from the journal by clicking on an entry but the module never implemented `journalresume` then it will end up there.

So, don't delete it, it is there to safeguard against bad messages flying around.

**Comment by Brahmanathaswami** [comment]
OK...close this for now. And open a new thread if another bugs comes alonsg
