### ISSUE TITLE
Internet Connectivity: No URL--Wrong File Error Checking

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#194]
Check the result after a URL call to the server. 

These are all direct path URLs in the SivaSiva app, and they never call a controller that the web site  uses for in own views (e.g. /view/TheGreatestBook).

If they have connectivity,  that url  will produce a 404 (I fixed, the problem  see below) 

Use the Surprise Me to test the function on cards
surprise_audio, surprise_video, surprise_darshan, surprise_art

If they have no connectivity, take then of verse, 

We need a function that

1) that informs the user they have no connectivity
use:

dialog_CustomMsg "Offline or Low Bandwidth"  

2) that case of connectivity, but the file is not present, have the  function to return "no-file" 
And Brahmanathaswami will implement what should happen in various modules.

------------
NOTE OUR 404 PAGE

see: 
/system/application/ha/config/route.lc
/system/application/ha/controllers/redirecterrorpage.lc

1. our route.lc uses this:

put "redirecterrorpage/aagRedirectIfFound" into gRoute[1]["404Override"]

2. We take control of the 404 by first checking on the redirect.xml
3. If there is no redirect then we send a 404 page
4. But, you need to set the header for 404, the guy who wrote redirecterrorpage (ha! I wonder who is is) did not set the header, therefore it returned a 200  by default.

```rigLogMessage
 [snip]
  
"error", "302 Redirect match" && tPage &&"matched"&& tFrom &&"redirected to --> " & tNewLink 
	put cr & the internet date & ": " & tPage after url ("file:" & $_SERVER["DOCUMENT_ROOT"] &  "/system/logs/404s_redirected.log")`

	put header "Status: 302"
	put header "Location:" && tNewLink
	put "Redirecting to" && tNewLink
	rigLogMessage "Redirect-to:", tNewLink
	
 end aagRedirectIfFound

	command sendCustomErrorPage tPage
	put tPage into gData["getRequest"]
	if tPage contains "taka/past" then 
		put  url ("file:" & $_SERVER["DOCUMENT_ROOT"] &"/html/info/taka-past.html")  into gData["singleArticle"]
			else
		put rigLoadView("sitewide/error-page",TRUE) into gData["singleArticle"]
	end if
		put "Kauai's Hindu Monastery - Page Note Found" into gData["pageTitle"] 
		put getSetHeadNav("skinny","Sorry, we could not find the page you were looking for",">Monastery<","") into gData["pageHeader"]		
		put header "Status: 404" # this line was missing.
		get rigLoadView("sitewide/two-column")  
	end sendCustomErrorPage```

**Comment by soapdog** [comment]
Made many fixes but still many things to fix.

**Comment by Brahmanathaswami** [comment]
One function that you deemed "deprecated" as still needed in case where

1) we could ping the server.
2) we need to determine if  the file actually exists on the server

function checkURLAvailable pSelectedURL     
   put  tsNetHeadSync(pSelectedURL, tSentHeaders, tResult, tBytes)  into tHeaders  # into tHeaders
   
   ## get url pSelectedURL
   if  (tResult is 200) then
      return true
   else
      ntInfo tResult && pSelectedURL
      return false
   end if
end checkURLAvailable

I did not understand how this was better:

function checkURLAvailable pSelectedURL     
   put  tsNetHeadSync(pSelectedURL, tSentHeaders, tResult, tBytes)  into tHeaders  # into tHeaders
   
   ## get url pSelectedURL
   if  (tResult is 200) then
      return true
   else
      ntInfo tResult && pSelectedURL
      return false
   end if
end checkURLAvailable
