### ISSUE TITLE
Word Puzzle Gives a Black Screen when Changing stacks

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#224]

**Comment by Brahmanathaswami** [comment]
I suspect this is universal based on the change of portal_GoStack:close module:open module procedure

**Comment by bwmilby** [comment]
Issue seems confined to landscape stacks (including normal websites when in landscape mode when the back icon is touched).

**Comment by Brahmanathaswami** [comment]
Not bug
