### ISSUE TITLE
Fix Browser Problem view_BrowserLandscape.livecode

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#227]
- the Browser : view_BrowserLandscape.livecode  is supposed to be used for video.
- open on landscape made and stay that way.
- The current code works but for one bug

1) first you have to start playing the movie
2) Then you turn the phone upright
3) the layout should fixed the landscape (it does on Android)
4) but on iOS the browser body change orientation to portrait, and to footer disappears. Not you user has no way "out" he is stuck on the app. and he must restart his phone..

5) perhaps the best solution is 
- let the "video" browser open in landscape
- then code it to footer appears in Portrait. then way the user can go out to home.

**Comment by Brahmanathaswami** [comment]
@bwmilby More discoveries: it is not really failing on iOS when we move the phone upright (portrait) on iOS. What is happening is
- We play the video
- YouTube switch to full screen mode
-  the browser widget on iOS (webket iOS...unlike Android) "honors" YouTubes full screen mode.
- when in full screenmode we lose the footer of our app!
- all you have to do is touch tne screen, and the video will "drop out" of full screen mode to show the controller for the video and our footer appears again. 
- the problem is:
  - use will not know this 
  - they think "no buttons of go home.
  - they think the are stuck in the app with No Where To Go.

SOLUTIONS: 
  - NUMBER 1:   view_BrowserLandscape.livecode is  NEVER allowed to change of format/rect from landscape. If the user turns his phone upright he will continue to see that the vidoe is formattied the the "long way"  and he will in the footer in usual place "the long way"  If it switch to Full screenmode he will touch the screen and get our footer back. 
  - This is already happening on Android. We need the save behavior on iOS..
  - Possibly there is a setting URL query/param that I can use this embed code to call the YOUTube without full screen mode.  SEE /models/model_SivaSiva/mode_SivaSiva.json.... for the navigation map. i will test that myself.

BTW Our next big module is to provide robust access to out YouTube. We will deprecate the Look TOC and go straight to the new module (as we do with LISTEN) that why we want the browser, in landscape mode to work. If will be very important later.

**Comment by bwmilby** [comment]
It looks like this is going to require a change to the Browser object in LC (`UIWebView`).  `allowsInlineMediaPlayback` needs to be set to `TRUE` for the embed option to be recognized.  It defaults to `TRUE` on iPad, but `FALSE` on iPhone.  I will push a change today that will fix it for iPad - not sure how an Android device will treat it though (should just get ignored).

`?playsinline=1` or `&playsinline=1` is what needs to be added to the end of the youtube embed URL (with the above property set).

This is the Apple dev document that I'm referencing:
https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1614793-allowsinlinemediaplayback?language=objc

YouTube Player  parameters:
https://developers.google.com/youtube/player_parameters

**Comment by Brahmanathaswami** [comment]
FOR reference :
https://developers.google.com/youtube/player_parameters

OK, I get it. Untll then, if you can prevent orientation change on the iPhone, for 
 
view_BrowserLandscape.livecode

when they turn their phone upright, so it behaves like Android

 that would suffice for now.

**Comment by bwmilby** [comment]
PR #228 partially addresses this issue.  For iPad, the content will remain landscape.

**Comment by Brahmanathaswami** [comment]
Pending patch from LIVE Code

**Comment by Brahmanathaswami** [comment]
Did we create a ticket Quality Control in LC... ? I don't see a fix into 9.5 release notes

**Comment by Brahmanathaswami** [comment]
@bwmilby 

Working on git hub issues, updating, closing etc.  and making a roadmap... I believe this issue was solved in 9.6? Right?

**Comment by Brahmanathaswami** [comment]
good to go
