### ISSUE TITLE
Responsive Architecture

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#231]
That's not a precise requirement, I will get you be to be creative for solutions.

Make a branch, 

 - Consider using my lib_UIHandler.livecodescript
 - I was going to have a "local" behavior (and a per stack basis) use a "updateUI" handler that the developer of the stack can use to call lib_UIHandler.livecodescript to place objects.
- lib_UIHandler.livecodescript also scale and resized images based on the card rect
- Kind of like a CSS for Livecode UI was my way of thinking about it.

But, perhaps

  - Siva-Siva-Portal -- Home Card what to NOT use the status bar, but have the background and image flow to and bottom. Of course we will have the keep the footer of the bottom bar.
 - You  can you the follow modules as a test bed
   - Siva-Siva-Portal.livecode # don't  forget cd Surprise
  - gems.livecode
  - surprise.livecode
  - daily-lesson.livecode

If those come easy you can work on others.

**Comment by bwmilby** [comment]
Screenshots taken on iPhone X simulator.

![image](https://user-images.githubusercontent.com/29169921/60314089-65168c80-992f-11e9-9c52-28d382cb646d.png)  ![image](https://user-images.githubusercontent.com/29169921/60314095-6b0c6d80-992f-11e9-8ac0-11a6786004db.png)  
![image](https://user-images.githubusercontent.com/29169921/60314105-72337b80-992f-11e9-9576-05096694987d.png)  ![image](https://user-images.githubusercontent.com/29169921/60314128-88413c00-992f-11e9-930a-a400023316b0.png)

Work being done in branch `bwm-responsive-1`

**Comment by Brahmanathaswami** [comment]
I loaded this on my iPhone XR, we see the following issues

 [ ] The label text of the data grid if off center vertically. It is shifted up.
 [ ] On the home "narrative" (currently a slide show with a pix follow by quote etc) click on the right arrow to go next: We can gett a flash of the content as it render twice. 
 [ ] When we go to anothe stack and come back to the portal, the content is scene shifted up, then one shift downs. I think you need a lockscreen in there. OR this will be away when we have to portal open (card will no need to re-rendered)
[ ] going to Journal > click Word Puzzle > it rendered is completely off. It loads landscape, but the content is scale done and shifted to right. Create a new puzzle removes control from the screen there is no way to portal. I need to kill to app and reboot it to get out.
This was working before since it was laid landscape, using the LC command to set the rect, mobileSetFullScreenRectForOrientations "landscape left,landscape right","0,0,667,375"
without using a UI library. But then  rebooted the app and the word puzzle is now the right place! This does happen if we do Word Puzzle for Portal. This is something peculiar what when Journal calls the Word Puzzle 

![2019-06-29_04-02-37](https://user-images.githubusercontent.com/3675722/60385242-dc791880-9a22-11e9-849d-1f2c6a65562a.png)

 [ ] There are instances where resuming the app (and perhap other instance) goes to the  e a white screen, if you click on get a different image: small with screen scale up and to the right and a black background.


![2019-06-29_04-10-58](https://user-images.githubusercontent.com/3675722/60385355-fd8e3900-9a23-11e9-8596-4a277f4fdbf4.png)

**Comment by Brahmanathaswami** [comment]
@bwmilby 
Testing: Android: 
>-Portal
>-Surprise
>- Back to Portal Stack/Card "Surprise"
>- click to go back the Nav Panel:
ERROR  in behavior_createMobileScroller
line 27. "can't find object"

**Comment by Brahmanathaswami** [comment]
Siva Siva Portal | Card "surprise"  | group "SivaSiva Portal Navigation.

[ the architect as legacy... we should have a, have a upgrade, to where with script ii  a group....call the target.... until then put these into

Widget "go home portal"
and
graphic "go home portal"

on mouseUp
   deleteAllMobileControls
   go to card "mainNav"
end mouseUp

**Comment by Brahmanathaswami** [comment]
The Moto G6 comes with an 18:9 aspect ratio display, and that's an IPS LCD at 5.7 inches. You get a Full HD+ resolution, so it's slightly higher than Full HD phones because of the taller screen size.4 days ago

![2019-07-19_10-40-21](https://user-images.githubusercontent.com/3675722/61564203-9efc1f80-aa11-11e9-87ed-9a17772c72ef.png)

**Comment by Brahmanathaswami** [comment]
stack: behavior_updatePortalUI

handler: UpdateUiPortal

Line 24-25

 put the long id of group "audioGlobalControl" of me into pControl
   topRightMe pControl,40,15

# that should be far away from any other matter...

**Comment by bwmilby** [comment]
> Siva Siva Portal | Card "surprise" | group "SivaSiva Portal Navigation.

Added `deleteAllMobileControls` to a closeCard handler in the behavior for the stack.  I understand why it would cause an issue, but I was unable to reproduce the error.

Updated location of `audioGlobalControl`.

**Comment by Brahmanathaswami** [comment]
Perhaps it does not show in up the simulator.

**Comment by bwmilby** [comment]
I tried on the Pixel as well.  In either case, the closeCard will take care of it now (or it should).

The Moto image reveals that I'm going to need to position/size all of the elements on the main nav card to have them look right on all devices.  Due to the virtual buttons at the bottom, the screen is cramped and the nav buttons (images) will need to be a bit smaller.

**Comment by Brahmanathaswami** [comment]
go for it....

**Comment by Brahmanathaswami** [comment]
As of Sept. 30, going back to the portal stack from a landscape stack causes
1. Render re-draw (that the user sees) or portrait, but content is skew "landscape" and still fit inside the screen (bizarre)
2. The cause the content and icons to be squished and distorted... a brief flash
3. then the portal stack in rendered.

WE need to somehow solve that

**Comment by Brahmanathaswami** [comment]
Brain, I am closing this issue. 
1. it too generic and we are beyond it now. 
2. Everything here is depracated UI
