### ISSUE TITLE
Try keeping Siva-Siva-Portal.livecode open

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#235]

**Comment by Brahmanathaswami** [comment]
put a condition in the main navigation library: lib_SivaSivaPortal.livecodescript. to keep open the Siva-Siva-Portal.livecode, to 
 - see if we get improvements on responsiveness
 - see if we can get some analysis of the RAM it takes up

**Comment by bwmilby** [comment]
Need to test more but I think it helps iOS and hurts Android.  I changed the binary in my branch.  I think I need to add a couple of check boxes so it is easy to test with variations of the settings.

**Comment by Brahmanathaswami** [comment]
did we decide on this yet? as of Nightly Aug 2, we are keeping the portal stack close when we go to another stack. If that is a decision (seems better in the long run for small CPU and RAM devices on Android) that we can close this issue

**Comment by bwmilby** [comment]
On Android this did not show any benefit.  On iOS it does in some cases (jumping main nav mainly).  Will keep the portal stack in memory selectively on iOS where it improves presentation (already implemented).
