### ISSUE TITLE
Move Browser to a card in Siva-Siva-Siva.livecode

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#236]
[ ] remains open 
 [ ] we can you a custom prop to change to landscape

**Comment by Brahmanathaswami** [comment]
We decided against this after experimentation are least we do not see an substack called "Browser " as a substack on Siva-Siva-Portal or in the Siva-Siva-App stack. Close this is that  is the case.

**Comment by Brahmanathaswami** [comment]
Close this if it a wrap

**Comment by bwmilby** [comment]
I think that there would be too much work at this time.  So much of the navigation depends on moving between stacks currently.
