### ISSUE TITLE
Test Branch "upgradeNarrative"

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#244]
test upgradeNarrative. See in you get a crash on a fresh in stall on android. the brand image will update every four minutes (240 seconds) ... for testing, we will change that in 1800 second when we produce the next version (a constant liv_SivaSiva)

also if you can reproduce the "stop" when to LTE, let me know the steps. I will also look it again. I think if you go to surprise, in get now art and photos from the server, ... could be something there....

**Comment by bwmilby** [comment]
Loaded branch on Android Pixel.

- There were a few cases where the screen would clear (just green background) and there would be a delay before the image was displayed.
- In the second story, several verses were repeated a couple times.

The first story went all the way through without problems and landed back at the home screen.  The second story went through as well and ended up on the home screen.

**Comment by Brahmanathaswami** [comment]
Yes, I found to we came up with a "clear screen" also, as if the mainimage was left invisible. 
I will check on the duplicate verses. good ...the stories worked as expected ....hope you enjoyed Saint Auvaiyar (old woman) she was a master at handing out basic human ethics. "Do not associate with people who are like snakes" :-)
