### ISSUE TITLE
Make Demo Stack Show to Problem Going Landscape to Portrait

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#246]
[  ] Create a  demo stack that shows our problem going to from a landscape stack to a portrait; with the weird rendering of content that appears on the way through the changes.
 [  ] put this on the official QA for LiveCode as a bug
 [  ] then me also so I can submit also on my business license support (hopefully they prioritize based on this)

**Comment by bwmilby** [comment]
Bug 22408 submitted on LC BugZilla
https://quality.livecode.com/show_bug.cgi?id=22408
