### ISSUE TITLE
Lexicon is Broken on Android - File a Bug Report and Sample Stack

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#259]
Please use 9.6.0 (dp3) going forward

  [  ] Make a branch from Nightly. call it lexiconJSHandlersBug
  [  ] create a standalone for Android
  [  ] confirm that the Javascript handler for search, etc pn Lexicon are not working
  [  ] submit a bug report, an quality control side, tell them "The same stack to use is SivaSiva>>lexiconJSHandlersBug>>go to Read>>Lexicon

Tell them work fine on iOS, but is now broken on android

**Comment by soapdog** [comment]
I just sent you and Heather an email. My LC indy subscription is not working, I can't work on this task without it.

**Comment by soapdog** [comment]
Finally got a recipe working. Will fill the bug

**Comment by soapdog** [comment]
Bug report: https://quality.livecode.com/show_bug.cgi?id=22668
