### ISSUE TITLE
Listen: change needed to download request dialog

### ISSUE THREAD

**Issue by soapdog** [Himalayan-Academy/Siva-Siva-App#280]
The message on the `downloadSelection` needs changing.

---
Original comment:

`Git` Push? I did not push. But you, or I can, push

We made a change to

behavior_Listen

command downloadSelection pSelectNum, pTarget
     setSelectNumber pSelectNum
     put the long id of pTarget into sLastTarget 
     if sSelectNum <> empty then # we have a selection
         doAnswer "Download this audio file? Also, &cr& "Journal entry requires a download.", "Download,Cancel","downloadAffirmed"
          else
         put "Pick a Title to Download It." into fld "currentTitleLabel"
     end if
end downloadSelection

_Originally posted by @Brahmanathaswami in https://github.com/Himalayan-Academy/Siva-Siva-App/issues/274#issuecomment-813434340_

**Comment by Brahmanathaswami** [comment]
We fix this
