### ISSUE TITLE
Listen: bug in hideDownloadControls

### ISSUE THREAD

**Issue by soapdog** [Himalayan-Academy/Siva-Siva-App#281]
It needs to hide group "downloadSelection" in handler `hideDownloadControls`.
---

Original message: 

Git Push? I did not push. But you, or I can, push

We made a change to

In grp “downloadControls” in behavior_Download;
we hide the grp 'downloadSelection" as we have download it

on hidedDownloadControls
     local tLastStack
     put empty into fld "ProgressTitle"
     put empty into fld "progressField"
     hide scrollbar "progressbar"
      hide grp "downloadControls"
      hide grp "downloadSelection"
end hidedDownloadControls`

_Originally posted by @Brahmanathaswami in https://github.com/Himalayan-Academy/Siva-Siva-App/issues/274#issuecomment-813443888_

**Comment by Brahmanathaswami** [comment]
We added this  handler to bug request, a file which is downloaded not longer the appearance of the 

<img width="414" alt="image" src="https://user-images.githubusercontent.com/3675722/115133210-1aea1980-9fa2-11eb-9734-21cc02294317.png">

which will be gone

<img width="414" alt="image" src="https://user-images.githubusercontent.com/3675722/115133229-466d0400-9fa2-11eb-9002-7d05ca3a09ec.png">


file:  modules/listen/behavior_Listen.livecodescript
added: 

`on hideDownloadControls
   local tLastStack
   put empty into fld "ProgressTitle"
   put empty into fld "progressField"
   hide scrollbar "progressbar"
   hide grp "downloadSelection"
   hide grp "downloadControls"
end hideDownloadControls`

and 

modules/listen/listen.livecode
       card "listen-file"
          group "downloadSelection"
                 behaviors/behavior_Download.livecodescript
file: behaviors/behavior_Download.livecodescript
changes:
 
`command downloadComplete pURL, pStatus
[snip}
   unload pURL
      
      delete word 1 to 4 of sRequestedBy
      dispatch "updateCachedListings"  to sRequestedBy with sRecordNumber
-- added this, which is called from 
-- modules/listen/behavior_Listen.livecodescript
      hideDownloadControls
      put removeQuotes(sRequestedBy) into tModule     
      tracking_RecordActivity tModule,"download/saved"
   end if
end downloadComplete`
