### ISSUE TITLE
Listen: possible duration bug

### ISSUE THREAD

**Issue by soapdog** [Himalayan-Academy/Siva-Siva-App#283]
THE Desktop version:  we get a durattion
 
 THE Mobile version: we see the  duration show "00:00:00"

_Originally posted by @Brahmanathaswami in https://github.com/Himalayan-Academy/Siva-Siva-App/issues/274#issuecomment-813468246_

**Comment by soapdog** [comment]
This bug is not clear to me. I don't know what duration we're talking about and how the bug manifests. Is this about the current position of the track during playback? the total track duration during playback? some timestamp display on the journal?

@Brahmanathaswami please add some more context and if possible a screenshot demonstrating this bug so that I understand better what I need to fix.

**Comment by Brahmanathaswami** [comment]
it is only the Mobile Version

Here is a picture from my iPhone

![IMG_2193](https://user-images.githubusercontent.com/3675722/113794101-805a2280-96e5-11eb-83c0-647fafeedb9e.PNG)

**Comment by soapdog** [comment]
Okay! Thanks for the explanation, working on it.

**Comment by soapdog** [comment]
I'm having a hard time reproducing this because it is working fine on my android device.

![photo_2021-04-07 12 34 05](https://user-images.githubusercontent.com/23247/113860107-90cdd400-979d-11eb-870d-452fc204fdc4.jpeg)

I suspect that a number of things are happening:

* All the URLs in the app need to be `https://` which they were not. Apple requires the usage of secure URLs.
* The URLs used by the app are not whitelisted in the standalone application settings.
* The app makes a bunch of requests when it launches and when the listen module launches. I suspect that later requests are failing not because there is no network access but because the previous requests have not completed. The code never checks for this option and assumes the requests will only fail if the network fails, which is not true.

**Comment by soapdog** [comment]
I've pushed an update just changing the URLs to be HTTPS. I can't reproduce this bug and since there is no difference in the code between Android and iOS this is probably a LC engine bug regarding `mobileControlGet('audioplayer','duration')` in iOS.

**Comment by Brahmanathaswami** [comment]
https://github.com/Himalayan-Academy/Siva-Siva-App/issues/288

put mobileControlGet("audioPlayer","playableDuration") into sDuration
         
         We heard from Elanor.
