### ISSUE TITLE
Stories: Nightly: Testing Portrait and Landscape - Nav scrubbing/tapping around the images

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#289]
Mobile, testing on my iPhone Xs

Using "Largest Religious Gathering in the World"reg

"The zoom sequence is backwards.  It is fine on the next image though."
What is backward? It seems fine to me 25%, 50%, 75%, full-sized

1) Portrait image - width over height which is largest

Portrait Orientation: 

25% (first tap on screen)
     - should be center on screen

50% (second tap on screen)
     - it scrolls left to right 
     - it DOESN'T scroll top to bottom

75%  (third tap on screen)
     - it scrolls left to right 
     - it does scroll top to bottom
     - we "good to go"

Full-Sized (fourth tap a screen)
     - it scrolls left to right 
     - it does scroll top to bottom
     - we "good to go"
     
Landscape Orientation: 

25% (first tap on screen)
   -should be center on screen
  
50% (second tap on screen)
     - should be center on screen
     - it does scroll top to bottom
     - we "good to go" except for center on screen

75%  (third tap on screen)
     - should be center on screen
     - it does scroll top to bottom
     - we "good to go" except for center on screen
  
Full-Sized (fourth tap a screen)
     - should be center on screen
     - it does scroll top to bottom
     - we "good to go" except for center on screen

2) Landscape Image - width which largest over height

Portrait Orientation: 

25% (first tap on screen)
     - should be center on screen
     - it does scroll left  to right
     - we "good to go" except for center on screen

50% (second tap on screen)
     - should be center on screen
     - it does scroll left  to right
     - we "good to go" except for center on screen

75%  (third tap on screen)
     - we "good to go" except for center on screen
  
Full-Sized (fourth tap a screen)
     - it scrolls to left to rght
     - it does scroll top to bottom
     - we "good to go" 
 
Landscape Orientation: 

We are "good to go" : top/bottom - left/right!

25% (first tap on screen)
     - it scrolls to left to rght
     - it does scroll top to bottom
     - we "good to go" 
  
50% (second tap on screen)
      - it scrolls to left to rght
     - it does scroll top to bottom
     - we "good to go" 
     
75%  (third tap on screen)
     - it scrolls to left to rght
     - it does scroll top to bottom
     - we "good to go" 
  
Full-Sized (fourth tap a screen)
       - it scrolls to left to rght
     - it does scroll top to bottom
     - we "good to go"

**Comment by bwmilby** [comment]
TODO:  Investigate if possible to actually adjust the scroll to fully keep image centered when zooming.

So far, whenever attempting to set the scroll to something other than topLeft, the part of the image the the left and above 0,0 becomes unreachable.  Rather than spend too much time trying things on my own, I think it would be good to ask the list for advice.

**Comment by bwmilby** [comment]
Ready for testing.

**Comment by Brahmanathaswami** [comment]
tested, Job is done! Hurray!
