### ISSUE TITLE
Stories: Go portrait, picture is bigger, go landscape, unresponsive to tapping

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#293]
it leaves no control. Unresponsive, you have no choice but to force quit the app.

**Comment by bwmilby** [comment]
This issue does not appear on my Pixel when built with LC 9.6.1

**Comment by bwmilby** [comment]
Corrected an issue where background behind text didn't adjust when device rotated.
Able to reproduce problem on iPhone; does not impact Android.
Whenever the device is rotated while the image is zoomed (which means a scroller is present), it locks up the app.

**Comment by bwmilby** [comment]
Found a scroller issue with the body text (scroller wasn't updated properly when rotated).
Still not sure why the app is locking on iOS when rotated with full screen scroller enabled.  Based on how the image is resized/positioned, it looks like the code is getting to the point where it should be updating the scroller.
