### ISSUE TITLE
Listen: Failure to Bring Journal to Advance by the sTimeStamp

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#311]
when you apply

modules/listen/behavior_Listen.livecodescript

on journalResume pDataA, pEntry
[snip}
 put pDataA into sDataA
 put path_FileFromURL(sDataA["url"]) into tURL
   
 put  sDataA["timestamp"] into sTimeStamp
   
# he register the sTimeStamp 
sTimeStamp  |  1724960

but how to get over to:

libraries/lib_MobileControls.livecodescript

they are started from the beginning :-(

**Comment by soapdog** [comment]
fixed in branch `error-handler-for-listen-module`.
