### ISSUE TITLE
DevHAP: Two Pages in Conflict  

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#318]

**Comment by Brahmanathaswami** [comment]
We have to the:


<img width="820" alt="2021-10-23_05-38-02" src="https://user-images.githubusercontent.com/3675722/138563096-19b1ff0f-70a6-4137-98e0-bfbc117440d4.png">

We etcs do with function like:

function extractSecondaryContentModule pNode
function extractHeroImagesModule pNode
function extractSidebarModule pNode

**Comment by Brahmanathaswami** [comment]
There's is one link 



`<module name="Tabbed Content Module">
    <title></title>
    <tab title="Hinduism Today">
			<item file_id="hinduism-today-current-issue" />
		</tab>
		<tab title="Educational Insights">
			<search media_type="book" file_id="_ei" />
			<search media_type="book" file_id="insight_" />
			
		</tab>
		<tab title="Scripture">
			<search media_type="book" tags="agama" />
			
			<item file_id="tirukural" />
			<item file_id="tirumantiram" />
			<item file_id="weavers-wisdom" />
		</tab>

		<tab title="Other Languages">
			<search media_type="book" language="french"/>
			<search media_type="book" language="spanish"/>
			<search media_type="book" language="sanskrit"/>
			<search media_type="book" language="tamil"/>
			<search media_type="book" language="malay"/>
			<search media_type="book" language="portuguese"/>
			<search media_type="book" language="german"/>
			<search media_type="book" language="russian"/>
			<search media_type="book" language="spanish"/>
			<search media_type="book" language="hungarian"/>
			<search media_type="book" language="ukrainian"/>
		</tab>
		<tab title="Complete List">
			<search media_type="text" />
		</tab>
	</module>
	<module name="Links Module">
		<collection>
			<title>Other Popular Resources</title>
			<links>
				<link url="/view/12-beliefs-of-saivism-russian_ru">Our Book Listed Vertically</link>
				<link url="/readlearn/panchangam">Our Hindu Calendar</link>`


<?xml` version="1.0"?>
<data>
	<module name="Featured Item Module">

		<media width="630" height="440" type="random" search="media_type:text" style="float: left;" />
		<cta type="link" url="/site/search/media_type/book">View all Books</cta>
	</module>


<module name="Tabbed Content Module">
	  <title>Browse Our Publications </title>
		<tab title="Our Gurus">
		        <search media_type="book" tags="our satgurus" />
		</tab>
		
                <tab title="For Teachers">
			<search media_type="book" title="history"/>
			<search media_type="book" tags="teachers" />

		</tab>
		<tab title="For Parents and Youth">
		        <search media_type="book" tags="parents" />
		        <search media_type="book" tags="teen" />
		        
			<search media_type="book" title="saivite hindu religion"/>
		</tab>
		<tab title="Childrens Books">
		        <search media_type="book" tags="children" />
		</tab>

	</module>

<module name="Tabbed Content Module">
    <title></title>
    <tab title="Hinduism Today">
			<item file_id="hinduism-today-current-issue" />
		</tab>
		<tab title="Educational Insights">
			<search media_type="book" file_id="_ei" />
			<search media_type="book" file_id="insight_" />
			
		</tab>
		<tab title="Scripture">
			<search media_type="book" tags="agama" />
			
			<item file_id="tirukural" />
			<item file_id="tirumantiram" />
			<item file_id="weavers-wisdom" />
		</tab>

		<tab title="Other Languages">
			<search media_type="book" language="french"/>
			<search media_type="book" language="spanish"/>
			<search media_type="book" language="sanskrit"/>
			<search media_type="book" language="tamil"/>
			<search media_type="book" language="malay"/>
			<search media_type="book" language="portuguese"/>
			<search media_type="book" language="german"/>
			<search media_type="book" language="russian"/>
			<search media_type="book" language="spanish"/>
			<search media_type="book" language="hungarian"/>
			<search media_type="book" language="ukrainian"/>
		</tab>
		<tab title="Complete List">
			<search media_type="text" />
		</tab>
	</module>
	<module name="Links Module">
		<collection>
			<title>Other Popular Resources</title>
			<links>
				<link url="/view/12-beliefs-of-saivism-russian_ru">Our Book Listed Vertically</link>
				<link url="/readlearn/panchangam">Our Hindu Calendar</link>
				<link url="/view/lexicon">Hindu Lexicon</link>
				<link url="/view/dancing-with-siva">Dancing with Siva</link>
				<link url="/view/living-with-siva">Living with Siva</link>
				<link url="/view/merging-with-siva">Merging with Siva</link>
				<link url="/view/hindu-basics">Hindu Basics</link>
				<link url="/view/loving-ganesha">The Elephant-faced God</link>
				<link url="/view/lemurian-scrolls">Lemurian Scrolls</link>
				 <link url="/readlearn/shum">Shum, The Language of Meditation</link>
			</links>
		</collection>
		<collection>
			<title>Quick Links</title>
		        <links>
				<link url="/readlearn/books/epub-info">How to Install ebooks</link>
				<link url="/livespiritually/become-student">Become a Student</link>
				<link url="/readlearn/basics">Basics of Hinduism</link>
				<link url="/livespiritually/meditation">Learning to Meditate</link>
				<link url="/monastery/about">About the Monastery</link>
				<link url="http://www.hinduismtoday.com/">Hinduism Today Magazine</link>
				<link url="/looklisten/art-photos">Art and Photo Galleries</link>
				<link url="/looklisten/chanting-songs">Chanting and Songs</link>
				<link url="/view/iraivan_2012-02-03_main-slide-show">Take a Virtual Tour</link>
				<link url="/livespiritually/monastic-life/how-to">How to Become a Monk</link>
				<link url="/looklisten/gurus-talks">Inspired Talks by Our Gurus</link>
				<link url="/readlearn/other-languages">In Other Languages</link>
				<link url="/readlearn/for-the-media">For the Media</link>
			</links>
		</collection>
	</module>
`

**Comment by Brahmanathaswami** [comment]
it does NOT appear!

<img width="1139" alt="2021-10-23_05-59-55" src="https://user-images.githubusercontent.com/3675722/138563372-e6381918-1fcc-4daf-b1ae-e5da5ac3ba56.png">

**Comment by soapdog** [comment]
Sorry Swami, but this issue is badly written and in the wrong repository. This is not related to Siva Siva App. Why is it in this repo?

You haven't said what the problem is. Please, describe without placing code in the issue, what is the problem. Answer two questions:

1. What should happen?
2. What is actually happening?

**Comment by soapdog** [comment]
There is a missing module in a page. Waiting for Swami to tell me which page.

**Comment by Brahmanathaswami** [comment]
https://dev.himalayanacademy.com/readlearn/books

**Comment by soapdog** [comment]
Swami,

You are trying to add a _links_ module to `html/readandlearn/books/index.xml`:

```xml
		<module name="Links Module">
			<collection>
				<title>Other Popular Resources</title>
				<links>
					<link url="/view/12-beliefs-of-saivism-russian_ru">Our Book Listed Vertically</link>
					<link url="/readlearn/panchangam">Our Hindu Calendar</link>
					<link url="/view/lexicon">Hindu Lexicon</link>
					<link url="/view/dancing-with-siva">Dancing with Siva</link>
					<link url="/view/living-with-siva">Living with Siva</link>
					<link url="/view/merging-with-siva">Merging with Siva</link>
					<link url="/view/hindu-basics">Hindu Basics</link>
					<link url="/view/loving-ganesha">The Elephant-faced God</link>
					<link url="/view/lemurian-scrolls">Lemurian Scrolls</link>
					<link url="/readlearn/shum">Shum, The Language of Meditation</link>
				</links>
			</collection>
			<collection>
				<title>Quick Links</title>
				<links>
					<link url="/readlearn/books/epub-info">How to Install ebooks</link>
					<link url="/livespiritually/become-student">Become a Student</link>
					<link url="/readlearn/basics">Basics of Hinduism</link>
					<link url="/livespiritually/meditation">Learning to Meditate</link>
					<link url="/monastery/about">About the Monastery</link>
					<link url="http://www.hinduismtoday.com/">Hinduism Today Magazine</link>
					<link url="/looklisten/art-photos">Art and Photo Galleries</link>
					<link url="/looklisten/chanting-songs">Chanting and Songs</link>
					<link url="/view/iraivan_2012-02-03_main-slide-show">Take a Virtual Tour</link>
					<link url="/livespiritually/monastic-life/how-to">How to Become a Monk</link>
					<link url="/looklisten/gurus-talks">Inspired Talks by Our Gurus</link>
					<link url="/readlearn/other-languages">In Other Languages</link>
					<link url="/readlearn/for-the-media">For the Media</link>
				</links>
			</collection>
		</module>
```

What you haven't realised is that that page is rendered by `sitewide/multiple-tabs.lc` view which doesn't support a links module. The listed links in the bottom are hardcoded into the view itself:

```html
	<div class="wrapper">
			
<section class="more-links">
				
					<div class="column">
					
						<h3 class="h3">Other Popular Resources</h3>
					
						<ul>
						 <li><a href="/readlearn/panchangam">Our Hindu Calendar</a></li>
<li><a href="/view/lexicon">Hindu Lexicon</a></li>
<li><a href="/view/dancing-with-siva">Dancing with Siva</a></li>
<li><a href="/view/living-with-siva">Living with Siva</a></li>
<li><a href="/view/merging-with-siva">Merging with Siva</a></li>
<li><a href="/view/hindu-basics">Hindu Basics</a></li>
<li><a href="/view/loving-ganesha">The Elephant-faced God</a></li>
<li><a href="/view/lemurian-scrolls">Lemurian Scrolls</a></li>
<li><a href="/readlearn/shum">Shum, The Language of Meditation</a></li>


						</ul>
					
					</div>
					
					<div class="column">
					
						<h3 class="h3">Quick Links</h3>
					
						<ul>
						<li><a href="/readlearn/books/epub-info">How to Install ebooks</a></li>
<li><a href="/livespiritually/become-student">Become a Student</a></li>
<li><a href="/readlearn/basics">Basics of Hinduism</a></li>
<li><a href="/livespiritually/meditation">Learning to Meditate</a></li>
<li><a href="/monastery/about">About the Monastery</a></li>
<li><a href="http://www.hinduismtoday.com/">Hinduism Today Magazine</a></li>
<li><a href="/looklisten/art-photos">Art and Photo Galleries</a></li>
<li><a href="/looklisten/chanting-songs">Chanting and Songs</a></li>
<li><a href="/view/iraivan_2012-02-03_main-slide-show">Take a Virtual Tour</a></li>
<li><a href="/livespiritually/monastic-life/how-to">How to Become a Monk</a></li>
<li><a href="/looklisten/gurus-talks">Inspired Talks by Our Gurus</a></li>
<li><a href="/readlearn/other-languages">In Other Languages</a></li>
<li><a href="/readlearn/for-the-media">For the Media</a></li>

						</ul>
					
					</div>
				
				</section> <!-- end more links -->
			
			</div>	
```

So we need to either fix that on the view by adding that link, or alter that view to fetch data from the xml. Which one do you prefer?

**Comment by Brahmanathaswami** [comment]
I think "or alter that view to fetch data from the xml." because why? Because we want to see it in the xml.

**Comment by Brahmanathaswami** [comment]
I removed the links control in /html/readlearn/books/index.xml and at added : https://docs.google.com/spreadsheets/d/e/2PACX-1vTVdnPQzxgqYlwqvo5otU7IXfS8t7CEdG938Osb-vpWCjzsHffCtmw1Hsv8bZGKMTBtGVchl5qa7PKK/pubhtml..... 

to: /application/ha/views/sitewide/multiple-tabs.lc

AND Both dev and HAP are the same
