### ISSUE TITLE
Bodhinatha's Latest is Failing

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#325]
sftp://192.81.132.79//home/devhap/public_html/application/ha/controllers/api3.lc

command getItemRecordsAndFormats

IS not working!

SivaSiva | Listen | behavior_Listen | on playList_FetchData pColl, pPlay , pFilterListQueryA, pBrowseHeader |   switch tPlaylistClass
      case "latest" 

showBusyIndicator true,"Loading Collection"

It only shows group "loadingGroup" and that its. It never goes further. We have to delete/remove the app from screen and try again.

else 
            breakpoint
            put it into tRecords
            put jsonToArray(tRecords) into sCurrentPlayListA["audioFiles"]
         end if

it simply goes "blank" !

You can try with nightly branch. Any other branch. Does not work. Shows the problem with server.

**Comment by soapdog** [comment]
I'll try to solve it tonight

**Comment by Brahmanathaswami** [comment]
Yes, even your phone, what branch it is, go 

Listen | Bodhinatha's Latest

and your "hung" ..."Loading Message" comes up...that's it
the json which wants to POST is so simple:

{"recordcount":30,"data":{"author":"Satguru Bodhinatha Veylanswami","media_type":"audio/inspiredtalk"},"recordType":"latest"}

l'll tackle that:

  command showBusyIndicator pBool, sMsg 

 so that it gracefully states "Cannot connect server." bails out takiing you to Collections....

**Comment by Brahmanathaswami** [comment]
Hmmm records are arriving! 
[snip]
         else 
            put it into tRecords
            --
            put tRecords
            --
            put jsonToArray(tRecords) into sCurrentPlayListA["audioFiles"]
         end if
         # add list type for other operations
         put tPlaylistClass into sCurrentPlayListA["playlistClass"]  #now we have our local array
         break

the 

put jsonToArray(tRecords) into sCurrentPlayListA["audioFiles"]

Doesn't work?

**Comment by Brahmanathaswami** [comment]
We are to close this ticket, We it because

"filename":"bd_2022-07-22_colors-magic-methods-for-self-improvement.mp3","

and audio_file_transcription was not JSON 

I took out -- Bodhinatha's Latest we passed listen-browse. No hang...
