### ISSUE TITLE
Add Sharing/Social to V1

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#55]

**Comment by Brahmanathaswami** [comment]
@soapdog 

FYI I did copy the libraries that David used for the Gurudeva app (which are yours!) over to 

/behaviors/behavior_SocialShare.livecodescript.

he basically used your code but added a layer e.g. it is customary pass a link to a web URL... And this was/is all working on the Gurudeva. 

So you can use (or scrap!) this code as you see fit.  but he also has the solution for Twitter, I don't for sure if that is working.

**Comment by soapdog** [comment]
We need to decide where in the interface sharing comes into play. Which are the shareable items? How the UI works? Sharing content is quite easy, deciding how it should behave is not as easy.

I do believe this should be added on V2, even though it is easy to do.

**Comment by Brahmanathaswami** [comment]
We planned for this to be in V1 from the beginning, I realize it requires thought. But we already have a model from the Gurudeva app. I'm willing to let Twitter go to V2, but we need facebook from day 1.
I can model the UI...we just have to focus on it... max 3 days.

**Comment by Brahmanathaswami** [comment]
Twitter is complicated with all the new "cards" and stuff. But face book is simple enough, even if we just share the web page for the Siva Siva app.  actually every  page the user is on, has a shareable image/or web link...

**Comment by soapdog** [comment]
We can't do Twitter. Or at least we couldn't, they used cryptography stuff that was not supported by LC, I may need to check again.

As for the thought part, we basically need to decide for each module, what are the shareable bits (if any)

**Comment by Brahmanathaswami** [comment]
Yeah, I know about Twitter they keep changing the API to stop spam, they dont' want app dev's generating tweets automatically, so they are making it harder and harder. later all we can do really is offer a button to take them to their twitter account or app, a let the user doe whatever he/she wants.. Facebook is easy.  But finish the journal first... i will map the content to share from all modules...

**Comment by Brahmanathaswami** [comment]
BTW, I added your library... it includes a few things from the Gurudeva app that David worked out...but we can take that our or re-purpose to SivaSiva

**Comment by soapdog** [comment]
Actually that is not the issue, the problem was that twitter rolled their OAuth 1.x implementation with their own crypto routines which were incompatible to what we had on LC, OAuth 2.x is compatible but I don't know if they moved to the new spec.

On a sidenote, we'll soon get into trouble as all the other platforms are moving from RESTful services with JSON into a new spec called GraphQL which LC doesn't support...

**Comment by Brahmanathaswami** [comment]
Add open graph tags tot he Siva Siva landing pages.

**Comment by Brahmanathaswami** [comment]
@soapdog closing for now... I put the add open graph tags into a separate task...
