### ISSUE TITLE
Journal: Add filtering options

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#58]

**Comment by Brahmanathaswami** [comment]
We probably need a way for use to add filter items later... the plabel and pTags for the items are in flux, so we may not know what we are looking. possible it may be better to allow the user to enter the filter themselves. We could have on filter which is a pull down for modules (this s a known list) and another field entry for use to filter.

**Comment by soapdog** [comment]
Already pushed the routines to add **filter by activity** still need to work  on **filter by date**.

**Comment by soapdog** [comment]
Adding to the issue, the options for the filter by date are:

* Today
* Last 3 Days 
* This Week 
* This Month
* Last 6 Months
* All

**Comment by Brahmanathaswami** [comment]
done
