### ISSUE TITLE
Journal: Pagination

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#59]
I set the journal to call 100 entries. this is going to make it slow to render. We need to think... perhaps pagination.. now sure what you had in mind. The filter probably need to look at the whole table back in time. Someone might want to see what they did 2 months ago...you probably though this through already

**Comment by soapdog** [comment]
Right now the journal routine is slow as molasses. I don't know why, I can see it rendered but the stack takes forever to return control to the user. I suspect that the rendering routine is being called more than once.

I am first trying to check if that is the case, then I will add pagination and filtering.

**Comment by soapdog** [comment]
Pagination routines are kinda ready. I am waiting for the UI work to be completed on the journal binary stack before adding it.

**Comment by soapdog** [comment]
We're not paginating, we're just fetching 100 records. We have code to paginate but it is not hooked to the UI. I don't know how desirable is this. We can simply fetch 300 records and use them. I don't see the need to go that back far in time. 

Thoughts? @Brahmanathaswami

**Comment by Brahmanathaswami** [comment]
Agreed: 300 is enough... no need to go farther back... later when we do some thing with badges and tracking progress etc. we can just read the entire dbase and get aggregate numbers like  "Path to Siva - Read 121 times) but no need to show all those!

**Comment by Brahmanathaswami** [comment]
@Andre Agreed no need to see more than 300 see above
