### ISSUE TITLE
Journal: Solve Passing Unicode Text to Journal pLabel and pTags

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#60]
see lib_SivaSivaBrowser  [there must be some way to link from code inside these comments]

you will the command on line 18 that sets the sLastPageTitle

If you set a break point, or push this to the message box, you will get the proper diacritial mark on top of, for example "Dancing with Siva" over the "S" character.

but when it goes the journal it is not unicode any more. I tried using TextDecode(tTitle,UTF-8) on the way through.. but it is not working... if you don't know about those commands, go look at

"lib_SivaSivaMedia" and you will see examples that work there.  But I don't know at what point youa re setting the field as you layout the journal on the repeat loop... over to you on this one.

**Comment by Brahmanathaswami** [comment]
Your best test suite is
Go to Gems  
click on the EYE to view the web context of the quote which is  page from a book. 
then look at the journal

There is also some bug where if the title is:

Dancing with Siva -- (mdash) it failes to be written the journal table.  even though i have checked carefully, it *is* getting passed


![2017-06-06_16-50-56](https://user-images.githubusercontent.com/3675722/26860240-a81b4aea-4ad8-11e7-8927-3592628e7fe8.jpeg)

**Comment by Brahmanathaswami** [comment]
but even though we pass "tTitle" as a proper param to the journal table, it fails to get entered.  

in the html generated by your NodeJS eBook parser the title  looks like this:

    <title>Merging with Śiva — </title

but never gets passed.

**Comment by soapdog** [comment]
![26860240-a81b4aea-4ad8-11e7-8927-3592628e7fe8 jpeg jpeg image 1202 x 577 pixels - nightly 2017-06-18 11 59 18](https://user-images.githubusercontent.com/23247/27261652-cb54a4ae-541d-11e7-9c85-20809271766f.png)

@Brahmanathaswami You're calling the function with the wrong parameters. You're passing a view where a module should be passed and a title where tags should be passed.

(Working on the unicode stuff)

**Comment by Brahmanathaswami** [comment]
@Andre  

1) view_SivaSivaBrowser.livecode *is* a binary stack (aka "module") and using this for this parameter is in fact working... try it click on the journal entry.. you go back to the browser, which is the expected behavior.

2) Agreed on Label vs Tags.. I need to re-think those.  in cases like this where the users is browsing the web, it should probably be something like

Label: Visiting Websites
Tag: tTitle (which by the way is taken from the web page itself. 

We can talk later... am meeting here.

**Comment by soapdog** [comment]
Fixed by changing the item template on the ```behavior_ItemTemplate``` so that it can render unicode chars and also fixing ```model_SivaSivaJournal``` so that the unicode stuff is passed correctly to the database.

Screen shot from the database:
![soapdog surfacefafi_ _mnt_c_users_soapdog_documents 2017-06-18 15 26 38](https://user-images.githubusercontent.com/23247/27263193-9d7bfd26-543a-11e7-951d-183db221cf55.png)

Screenshot from the journal:
![journal 1 _ 2017-06-18 15 27 38](https://user-images.githubusercontent.com/23247/27263200-acddc9fc-543a-11e7-97a5-348437584b0a.png)

Already pushed it to the **journal_work_and_fixes** branch.
