### ISSUE TITLE
Journal: Decision on Long Web Page Title

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#61]
Use Case: someone goes to a web page or a book page in the browser widget. Programatically we cannot always pre-set the tags for the journal entry. We only know the top level activity like "Read Book - Web" or "View Web Page" etc... but for the journal we need more specific detail other wise the entries are too generic to be meaningful  to the user.  I solve this, at least for now, with two functions.

1) the main navigation point is in lib_SivaSivaPortal ... I added a new param there to the 

command portal_GoUrl someURL,pJournalLabel

the developer can use this... it it not filled in, then we call the sLastLInkTitle which is the know label for the group int he portal rows.  

OTOH, when we go to a web page, it is logged in the journal.. the JournalResume by passes the portal_GoURL (deliberately) and we pass the title of the web page which we parse from the htmltext of the browser widget.  see lib_SivaSivaBrowser line 18
this is a "no brainer" and works just fine, but... it is often too long.

Probably I will truncate that title... we are using a two chunk output form our revIgniter controllers

Realm + local page

e.g. 

Kauai's Hindu Monastery - Monthly News

So, in the journal it just has room for

Kauai's Hindu Monast... # that's it. 

So we have to decide what to do. Easy enough to parse out the last part

put "-" into the itemdelimiter
 if (the number of items of tRawTile) > 1 then 
   delete item 1 of tRawTitle
end if

I'm not sure if that is a good idea and wanted you to think about it.

**Comment by soapdog** [comment]
@Brahmanathaswami in the future please use the appropriate styling for code in the issue text, you can simply highlight the code text and click the angle brackets on the toolbar above the editing area. It makes for easier reading.

We need to approach this problem from a systematic manner. Are our titles regular? Can we have a replacement routine that for example picks "Kauai's Hindu Monastery" and shorten it? Should we simply split the string by _-_ and pick the last item?

**Comment by Brahmanathaswami** [comment]
@soapdog 

Yes, the titles are regular but not always 2 pieces. 
Yes can split with "-"
Have to check first if there are 2 items. 
if not, just use 1, if 2 then use the last part.
of course the books are all just given the title of the book, nothing specific to the chapter. but I don't think that is a big issue.  Users know they were reading Dancing with Siva "somewhere around ch55" and when they click, it takes them back to that chapter... so if it doesn't show up on the label for now... not a big problem, they still go back to where they left off. 

But we have the issue of the same view_SivaSivaBrowser having the same title. for both web sites and book pages... but there are really to different classes of content/activity, from a user point of view.

**Comment by soapdog** [comment]
Can we close this one @Brahmanathaswami ?

**Comment by Brahmanathaswami** [comment]
Sure
