### ISSUE TITLE
Path to Siva: Fix the Info Text

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#62]
Remove references to map/realm navigation. 
Remove refenence to follow See Also words

**Comment by Brahmanathaswami** [comment]
@jacquegay  We need to remove the paragraph in the "info/about" test of Path to Siva that says:

"Exploring Realms"

Exploring realms displays a map..."

etc.. 

Obviously, not in V1!  Can you removed this, just pull nightly, fix and push back.. no one else is touching anything in that module.

**Comment by jacquegay** [comment]
Done
