### ISSUE TITLE
Android Can't Find Path to File

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#66]
@jacquegay 

Context: 
/modules/settings/settings.livecode  # card 1 with assigned behavior
# grp "display-info"  (has only generic handler in script but you can look at it) it is normally hidden

/behaviors/behavior_SivaSivaSettings.livecodescript

/libraries/lib_SivaSiva.livecodescript  
# see new simplified path functions 
in this case we are calling :  path_Assets()

Settings.livecode stack:

The group of buttons on the card... passes the mouse event via "the target" to the behavior.
the handler "displayInfo 1, "About"  is triggered. we also fire this from links inside the text itself. 
 

PARAMS:
 1 : 1 = vis is true # set the vis of the group "display-Info" which has it's own handlers. Check th groups 
2: string= used in a switch case statement. 

for these cases: About, Credits, Release Notes, Terms of Service Privacy and EULA

the displayInfo handler' switch statement fetches the path_assets() then appends the "info/release-note.html" and sets the HTML text of the field. then set the vis to true and creates a mobile scroller.

This is all working on desktop and iOS, but on Android. the field is blank. It's as if Android cannot find the html file.  I suspect myh handlers in lib_SivaSiva may not be working... but it *does* fetch the file name of the background image in path_Assets() & "img/backgrounds... etc." but for some weird reason, it cannot find the html files in /info/*.html?

**Comment by jacquegay** [comment]
Fixed path and pushed update. Also added a backKey handler to the settings card; without it the app quits on backKey.
